---
apiVersion: v1
kind: Secret
metadata:
  name: db-mariadb-galera
  namespace: "db"
  labels:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: db
type: Opaque
#note that write base64 encoded password in {data}, passwords will be decoded and set on database.
data:
  mariadb-root-password: "BASE64_ENCODED_ROOT_PASSWORD"
  mariadb-password: "BASE64_ENCODED_ROOT_PASSWORD"
  mariadb-galera-mariabackup-password: "BASE64_ENCODED_ROOT_PASSWORD"
