---
apiVersion: v1
kind: Service
metadata:
  name: db-mariadb-galera
  namespace: "db"
  labels:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: db
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: db
